
CREATE TABLE DEFENCE(
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL
);
INSERT INTO DEFENCE VALUES(20,'Captain Piett');
INSERT INTO DEFENCE VALUES(24,'General Veers');
INSERT INTO DEFENCE VALUES(56,'Admiral Ozzel');
INSERT INTO DEFENCE VALUES(88,'Commander Jerjerrod');

SELECT * FROM DEFENCE WHERE NAME='Genral Veers'